name       : nodejs
version    : 10.15.3
release    : 72
source     :
    - https://github.com/nodejs/node/archive/v10.15.3.tar.gz : e794782ea4ed72e9f5b3da5ecafc09da2118806af29dac14215a4e68344b3626
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libnghttp2)
    - pkgconfig(libssl)
    - pkgconfig(libuv)
    - pkgconfig(zlib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-running-gyp-on-shared-deps.patch
    ./configure --prefix=/usr \
        --shared-libuv \
        --shared-nghttp2 \
        --shared-zlib \
        --with-intl=system-icu
build      : |
    %make BUILDTYPE=Release
install    : |
    %make_install
    pushd $installdir/usr/include/node/openssl/archs/
    find * -maxdepth 0 -type d -not -name "linux-x86_64" -prune -exec rm -r '{}' \;
    popd
