name        : nodejs
version     : 4.1.1
release     : 7
source     :
    - https://github.com/nodejs/node/archive/v4.1.1.tar.gz : 186eead0e8089d54c0c6c3e76f9eb500e55b917b0b001c4823dccd8fd0615f0a
license     : MIT
summary     : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description : |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
