name        : nodejs
version     : 5.10.0
release     : 23
source     :
    - https://nodejs.org/dist/v5.10.0/node-v5.10.0.tar.xz : e3cc8e84b38b2d86ddf802f690eacabd97f5e32d37b9c70e19ecfdd2bef6e13a
license     : MIT
summary     : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description : |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/standalone.gypi
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/toolchain.gypi
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
