name        : nodejs
version     : 4.1.0
release     : 6
source     :
    - https://github.com/nodejs/node/archive/v4.1.0.tar.gz : cc4d4dd1dac5e282779bec8b0e207bc44a19902a53622e6a6dde37071276fa82
license     : MIT
summary     : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description : |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
