name        : nodejs
version     : 4.0.0
release     : 5
source     :
    - https://nodejs.org/dist/v4.0.0/node-v4.0.0.tar.gz : e110e5a066f3a6fe565ede7dd66f3727384b9b5c5fbf46f8db723d726e2f5900
license     : MIT
summary     : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description : |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
