name       : nodejs
version    : 6.5.0
release    : 29
source     :
    - https://nodejs.org/dist/v6.5.0/node-v6.5.0.tar.xz : ddf2056a9164c723db707b6c016f9e617f17166298dc88c5a7cb1d7d5ddb1290
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/standalone.gypi
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/toolchain.gypi
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
