name        : nodejs
version     : 5.4.1
release     : 15
source     :
    - https://nodejs.org/dist/v5.4.1/node-v5.4.1.tar.xz : 4e7d3fdfeac85c46ddaef0224695620f218e7a178e97d6e210d6d643483f1d53
license     : MIT
summary     : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description : |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
setup      : |
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/standalone.gypi
    sed -i "s/'linux_use_gold_flags%': 1,/'linux_use_gold_flags%': 0,/g" <<< "'linux_use_gold_flags%': 1," deps/v8/build/toolchain.gypi
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
