name       : nodejs
version    : 8.8.1
release    : 53
source     :
    - https://nodejs.org/dist/v8.8.1/node-v8.8.1.tar.gz : 1725bbbe623d6a13ee14522730dfc90eac1c9ebe9a0a8f4c3322a402dd7e75a2
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(libssl)
    - pkgconfig(zlib)
setup      : |
    ./configure --prefix=/usr \
        --shared-openssl \
        --shared-zlib
build      : |
    %make
install    : |
    %make_install
