name       : nodejs
version    : 14.16.1
release    : 94
source     :
    - https://github.com/nodejs/node/archive/v14.16.1.tar.gz : 418fb4277a2be53f40d4425e8a05151229af440828b384da13ced4ed1a979cbe
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(libnghttp2)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-running-gyp-on-shared-deps.patch
    %patch -p1 < $pkgfiles/0002-Suppress-NPM-message-to-run-global-update.patch
    ./configure --prefix=/usr --shared-nghttp2 --shared-zlib
build      : |
    %make BUILDTYPE=Release
install    : |
    %make_install
    pushd $installdir/usr/include/node/openssl/archs/
    find * -maxdepth 0 -type d -not -name "linux-x86_64" -prune -exec rm -r '{}' \;
    popd
    pushd $installdir/usr/lib/node_modules/npm/node_modules/
    find -path "*.md" -prune -exec rm -r '{}' \; \
        -or -name "AUTHOR*" -prune -exec rm -r '{}' \; \
        -or -name "LICENSE*" -prune -exec rm -r '{}' \; \
        -or -name "PULL*" -prune -exec rm -r '{}' \; \
        -or -name "Makefile" -prune -exec rm -r '{}' \; \
        -or -name "appveyor.yml" -prune -exec rm -r '{}' \; \
        -or -name "doc" -prune -exec rm -r '{}' \; \
        -or -name "docs" -prune -exec rm -r '{}' \; \
        -or -name "examples" -prune -exec rm -r '{}' \; \
        -or -name "license*" -prune -exec rm -r '{}' \; \
        -or -name "*.bak" -prune -exec rm -r '{}' \; \
        -or -name "*.d.ts" -prune -exec rm -r '{}' \; \
        -or -name "*.markdown" -prune -exec rm -r '{}' \; \
        -or -name ".*.yml" -prune -exec rm -r '{}' \; \
        -or -name ".editorconfig" -prune -exec rm -r '{}' \; \
        -or -name ".github" -prune -exec rm -r '{}' \; \
        -or -name ".nycrc" -prune -exec rm -r '{}' \;
    popd
    rm -rf $installdir/usr/lib/node_modules/npm/{changelogs,docs}
