name       : nodejs
version    : 8.6.0
release    : 50
source     :
    - https://nodejs.org/dist/v8.6.0/node-v8.6.0.tar.gz : 80551d47440c602c5825a3f6611e13cb0c57d277234dbff693af433a88351a08
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(libssl)
    - pkgconfig(zlib)
setup      : |
    ./configure --prefix=/usr \
        --shared-openssl \
        --shared-zlib
build      : |
    %make
install    : |
    %make_install
