name       : nodejs
version    : 8.9.1
release    : 55
source     :
    - https://nodejs.org/dist/v8.9.1/node-v8.9.1.tar.gz : 32491b7fcc4696b2cdead45c47e52ad16bbed8f78885d32e873952fee0f971e1
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(libssl)
    - pkgconfig(zlib)
setup      : |
    ./configure --prefix=/usr \
        --shared-openssl \
        --shared-zlib
build      : |
    %make
install    : |
    %make_install
