name       : nodejs
version    : 16.14.0
release    : 107
source     :
    - https://github.com/nodejs/node/archive/refs/tags/v16.14.0.tar.gz : b3f14c032ddcfd681aa4ee528d4017e5da646b93d53575427cb9dd4c133b1e0f
license    : MIT
component  : programming
summary    : Node.js is a platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications.
description: |
    Javascript platform to make fast, scalable network application. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libbrotlicommon)
    - pkgconfig(libcares)
    - pkgconfig(libuv)
    - pkgconfig(libnghttp2)
    - pkgconfig(openssl)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-running-gyp-on-shared-deps.patch
    %patch -p1 < $pkgfiles/0002-Suppress-NPM-message-to-run-global-update.patch
    ./configure \
        --prefix=%PREFIX% \
        --shared-brotli \
        --shared-cares \
        --shared-libuv \
        --shared-nghttp2 \
        --shared-openssl \
        --shared-zlib \
        --with-intl=system-icu
build      : |
    %make
install    : |
    %make_install
    find $installdir/usr/lib/node_modules/npm/node_modules \( \
        -name '*.md'     -o \
        -name 'AUTHOR*'  -o \
        -name 'LICENSE*' -o \
        -name 'PULL*'    -o \
        -name Makefile   -o \
        -name appveyor.yml -o \
        -name doc  -o \
        -name docs -o \
        -name examples -o \
        -name 'license*' -o \
        -name '*.bak'  -o \
        -name '*.d.ts' -o \
        -name '*.markdown' -o \
        -name '.*.yml' -o \
        -name .editorconfig -o \
        -name .github -o \
        -name .nycrc \
        \) -exec rm -rf {} +
    rm -rf $installdir/usr/lib/node_modules/npm/{changelogs,docs}
